package com.click4bonds.app.Modules.Bond.Service;

import java.time.LocalDate;
import java.util.List;
import java.util.Objects;

import org.springframework.stereotype.Service;

import com.click4bonds.app.Modules.Bond.Dto.CouponEvent;
import com.click4bonds.app.Modules.Bond.Models.Bond;

/**
 * Default {@link CouponEventResolver} that preserves the existing behaviour.
 *
 * <p>Coupon dates are generated by the existing {@link CouponDateGenerator} —
 * the same source the cash-flow pipeline already uses — and each is wrapped
 * into a {@link CouponEvent} with no record/ex-coupon dates set. This keeps
 * the current cum-coupon behaviour unchanged while establishing the events
 * that later record-date / ex-coupon logic can enrich.
 */
@Service
public class CouponEventResolverImpl implements CouponEventResolver {

    private final CouponDateGenerator couponDateGenerator;

    public CouponEventResolverImpl(CouponDateGenerator couponDateGenerator) {
        this.couponDateGenerator = Objects.requireNonNull(
                couponDateGenerator,
                "CouponDateGenerator is required");
    }

    @Override
    public List<CouponEvent> resolve(Bond bond, LocalDate calculationDate) {
        List<LocalDate> couponDates = couponDateGenerator.generate(
                bond,
                calculationDate);

        if (couponDates == null) {
            return List.of();
        }

        return couponDates.stream()
                .map(CouponEvent::of)
                .toList();
    }
}
