package com.click4bonds.app.Modules.Document.Service;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import com.click4bonds.app.Modules.Document.Model.DocumentFormat;

/**
 * Derives storage keys.
 *
 * <p>Keys are a pure function of the deal reference, the deal's date and the
 * format. That determinism is load-bearing rather than cosmetic: it means
 * regenerating a document for the same deal overwrites the previous file instead
 * of accumulating a second copy, so a retry after a failure is safe to run.</p>
 *
 * <p>The {@code yyyy/MM} prefix keeps a directory from growing without bound,
 * which matters on filesystems that degrade in large directories and when the
 * files are ever archived by hand.</p>
 */
public final class DocumentKeys {

    private static final DateTimeFormatter MONTH_PREFIX =
            DateTimeFormatter.ofPattern("yyyy/MM");

    private DocumentKeys() {
    }

    /**
     * The part of a key shared by every format of the same document.
     *
     * <p>Kept separate from {@link #forDeal} so the spreadsheet and the PDF of a
     * deal sit under one stem. Deriving the PDF's key by stripping the
     * spreadsheet's extension would work and be one more thing to get wrong.</p>
     *
     * @return a relative stem such as {@code 2026/09/DC-20260923-000001}
     */
    public static String stemForDeal(String dealReference, LocalDate dealDate) {

        return dealDate.format(MONTH_PREFIX)
                + "/"
                + safeSegment(dealReference);
    }

    /**
     * Builds the storage key for one format of a deal's document.
     *
     * @param dealReference the deal's customer-facing reference, e.g.
     *                      {@code DC-20260923-000001}
     * @param dealDate      date the key is filed under
     * @param format        format being stored
     * @return a relative key such as {@code 2026/09/DC-20260923-000001.pdf}
     */
    public static String forDeal(
            String dealReference,
            LocalDate dealDate,
            DocumentFormat format) {

        return stemForDeal(dealReference, dealDate)
                + "."
                + format.extension();
    }

    /**
     * Strips anything that could turn a key into a path escape.
     *
     * <p>A deal reference is generated by this application and cannot currently
     * contain a separator, so this is defence in depth rather than a live
     * concern — but the value reaches a filesystem write, and the cost of
     * checking is one regular expression.</p>
     */
    private static String safeSegment(String value) {

        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException("Deal reference is required to build a document key");
        }

        String cleaned = value.replaceAll("[^A-Za-z0-9._-]", "_");

        /*
         * "." and ".." survive the filter above and both mean a directory, so
         * they are rejected outright rather than rewritten into something that
         * silently points somewhere else.
         */
        if (cleaned.equals(".") || cleaned.equals("..")) {
            throw new IllegalArgumentException("Unusable deal reference for a document key: " + value);
        }

        return cleaned;
    }
}
